first implementation of upsert method
gophers-latam/GoKey pull request #6
Opened 2021-04-30 03:16 UTC by ManuelNinyo

upsert  method and test were implemented

2021-05-01 23:21 UTC, tomiok approved these changes

2021-05-02 01:54 UTC, tbuchaillot requested changes

2021-05-02 01:54 UTC, tbuchaillot commented on gokey/cache.go
> +	if ttl < 0 {
@ManuelNinyo Yo seguiria un poco la forma que maneja Redis (TTL -1 = no expira).

2021-05-05 21:38 UTC, tomiok commented on gokey/cache.go
> +	if ttl < 0 {
@ManuelNinyo queres cambiar esta validacion asi mergeamos?

2021-05-07 04:17 UTC, zeroidentidad commented on gokey/cache.go
> +	if ttl < 0 {
Se hicieron cambios para probar, queda duda de como sería el flujo validación adecuado

2021-05-07 04:43 UTC, tomiok commented on gokey/cache.go
> +	if ttl < 0 {
el ttl podria ser cualquier numero, aunque estandarizado a
-1/0 == no expira
>0 == expira en esa cantidad de milisegundos

2021-05-07 05:09 UTC, zeroidentidad commented on gokey/cache.go
> +	if ttl < 0 {
ok, veo se considera en cambios de los archivos https://github.com/gophers-latam/GoKey/pull/6/files se asignaria time.Duration = -1

viendo si se sigue logica de redis se considera una variable expiration que usa para calcularse variable ttl

2021-05-08 20:02 UTC, merged